### ISSUE TITLE
Explain the difference between renderSubview and registerSubview

### ISSUE THREAD

**Issue by mike-engel** [AmpersandJS/ampersand-view#104]
This is a minor issue, but it would be nice to provide a brief explanation about the difference between renderSubview and registerSubview. Basically state that renderSubview is a wrapper around registerSubview with some extra sugar (auto render then register).

If I get some time, I can create a PR, but if someone else can get this done before then, the better.

**Comment by kamilogorek** [comment]
@mike-engel isn't it all described here? :) https://github.com/AmpersandJS/ampersand-view/blob/master/README.md#registersubview-viewregistersubviewviewinstance

**Comment by mike-engel** [comment]
It is *to an extent*. I had a moment yesterday when I didn't understand the difference between the two methods and what each one was supposed to do. I'm just saying it would be nice to point out that renderSubview calls registerSubview and also does some other stuff.

**Comment by pgilad** [comment]
@mike-engel I agree the methods could be better described.
In the minimal technical aspect:

`registerSubview` does:
- add subview to `_subviews` array
- assign parent view as parent of the given subview

`renderSubview`:
- `registerSubview`
- render subview
- append rendered subview to container if given, otherwise to `this.el`

Would that description suffice a good explanation?
I seriously believe code-reading https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L214-L235 is the **best** solution, but for the quick-reference maybe that description works.

**Comment by mike-engel** [comment]
Looks good to me @pgilad.

**Comment by pgilad** [comment]
@kamilogorek How should we edit ^ in?

**Comment by kamilogorek** [comment]
@pgilad what do you exactly mean by `how`?
