### ISSUE TITLE
cacheElements with queryAll

### ISSUE THREAD

**Issue by vwasteels** [AmpersandJS/ampersand-view#107]
Is there a way to use ```this.cacheElements()```to cache a set of elements ?

for now I  have to do it manually :

```js
	render: function() {
		this.renderWithTemplate();
		this.socialContentsEl = this.queryAll('.tile-social-content [class^="tile-social-"]');
	},
```

and i'd like to do it that way :

```js
	render: function() {
		this.renderWithTemplate();
		this.socialContentsEl({
		    : '.tile-social-content [class^="tile-social-"]',
		  });
	},
```

but in this case, ```this.socialContentsEl``` returns the first element only

**Comment by cdaringe** [comment]
hey @vwasteels, [per the source](https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L332) there is not.  Because of the ambiguity & uncertainty of the returned elements, &-js would not know *how* you would like those cached.  I.e. how would your elements get stored onto obj? `this.titleSocial1`?, `this.title_social_el_0`?, etc etc. I'd recommend that you add a sugar function to do the query, and index on key definitions as you see fit.

Let me know if that was unclear!  If you have an idea about a standard way to do it that could be beneficial, please share. :smile:
