### ISSUE TITLE
Is there any documentation for how to wire up Ampersand views to work with Marionette?

### ISSUE THREAD

**Issue by dschissler** [AmpersandJS/ampersand-view#121]
I'm using webpack and I'm wondering how to wire up Marionette to use Ampersand views instead of Backbone for CommonJS.  Is there any documentation or examples for this?

**Comment by mmacaula** [comment]
hey @dschissler, if I read your question right, are you asking to have Marionette use AmpersandView as the view it extends from, instead of Backbone.View?  I don't believe that would be possible without some javascript ninja stuff via playing with the prototype chain, or alternatively forking Marionette and changing what their views `extend` from.  

It is possible to use Ampersand and Marionette together though, I've been doing it for the past year.  The view's all have a similar api (render, remove) so you can render a marionette view as an ampersand subview or have marionette regions `show` ampersand views.
